### ISSUE TITLE
Problem with 'Raising issues with Reliability Engineering'

### ISSUE THREAD

**Issue by emilygds** [alphagov/govuk-developer-docs#1000]
Problem with 'Raising issues with Reliability Engineering' (https://docs.publishing.service.gov.uk/manual/raising-issues-with-reliability-engineering.html)

"Who do I ask for support?" link is broken.

**Comment by kevindew** [comment]
Thanks - PR for this: https://github.com/alphagov/govuk-developer-docs/pull/1001
