### ISSUE TITLE
Problem with tunnelling instructions

### ISSUE THREAD

**Issue by MatMoore** [alphagov/govuk-developer-docs#1015]
I've noticed that other developers are not able to use the ssh commands in some of the manual pages, eg the integration command here https://docs.publishing.service.gov.uk/manual/rabbitmq.html#header

This is because `ssh integration` doesn't work for them.

In my ssh config I have an integration host defined as

```
Host integration
  Hostname jumpbox.integration.publishing.service.gov.uk
```

But this is not in the example config here:

https://github.com/alphagov/govuk-puppet/blob/master/development-vm/ssh_config

We could fix this by changing the example and/or changing the docs. I'm just creating the issue to keep track of this as I don't have time to fix right now. Does anyone have any opinions on how this should work?

**Comment by thomasleese** [comment]
Sounds like that file in `govuk-puppet` needs to be made up to date with https://docs.publishing.service.gov.uk/manual/ssh-config.html#header or the other way around...

**Comment by MatMoore** [comment]
Ah I wasn't even aware of that one. The getting started guide links directly to the file in github: https://docs.publishing.service.gov.uk/manual/get-started.html#6-access-remote-environments

**Comment by issyl0** [comment]
Looks like this was fixed in 2018. Closing.
