### ISSUE TITLE
Re: 'Deploy Puppet'

### ISSUE THREAD

**Issue by binaryberry** [alphagov/govuk-developer-docs#1275]
When trying to run the ./bin/puppet_versions.sh script on staging, I get this error:

```
Traceback (most recent call last):
  File "bin/show_puppet_versions.py", line 6, in <module>
    import requests_cache
ImportError: No module named requests_cache
``` 

Problem with 'Deploy Puppet' (https://docs.publishing.service.gov.uk/manual/deploy-puppet.html)

**Comment by deanwilson** [comment]
I've not seen this bug mentioned recently and the raiser of this issue has moved onwards and upwards so I'm closing it. I'm happy to reopen it if binaryberry comes back to us 0:)
