### ISSUE TITLE
Recommend upgrading your pact roker

### ISSUE THREAD

**Issue by bethesque** [alphagov/govuk-developer-docs#1468]
Problem with 'Pact Broker' (https://docs.publishing.service.gov.uk/manual/pact-broker.html)

Hi, I am one of the maintainers of the Pact Broker open source project. I notice that you are running a very old version of the broker (I can tell because your index redirects to `ui/relationships` which it hasn't done for quite a while). There have been vulnerabilities found in old versions of the broker, so I recommend that you upgrade to the latest version. Please feel free to email me if you wish to discuss details.

**Comment by tijmenb** [comment]
Hi @bethesque! Thanks so much for bringing raising this. We've enabled automatic dependencies upgrades for pact-broker, upgraded to the latest version (https://github.com/alphagov/govuk-pact-broker/pull/3) and added the app to our documentation (https://github.com/alphagov/govuk-developer-docs/pull/1469). That should prevent us from getting too far behind again. Thanks again, and thanks for Pact Broker! 🙇

**Comment by bethesque** [comment]
No worries. Glad it's useful for you!
