### ISSUE TITLE
Markdown list rendering incorrect

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-developer-docs#153]
Markdown doc on github

![image](https://cloud.githubusercontent.com/assets/2445413/25176146/1eacc4cc-24f5-11e7-866d-d2532cc64872.png)

vs

![image](https://cloud.githubusercontent.com/assets/2445413/25176133/174a2b34-24f5-11e7-8e62-9bf210b84864.png)

**Comment by tijmenb** [comment]
Fixed this particular issue in https://github.com/alphagov/govuk-developer-docs/pull/195.
