### ISSUE TITLE
History links to removed paths

### ISSUE THREAD

**Issue by nickcolley** [alphagov/govuk-developer-docs#154]
In https://docs.publishing.service.gov.uk/manual/retiring-an-application.html it refers to https://github.gds/gds/opsmanual/tree/master/infrastructure/howto/retiring-an-application.md

We should link to a commit-ish slug rather than HEAD

**Comment by tijmenb** [comment]
Would've been a good idea, I don't think we can do this anymore. In any case, looks like we won't refer back to the opsmanual that much anyway.
