### ISSUE TITLE
Add support info for licensing apps

### ISSUE THREAD

**Issue by benthorner** [alphagov/govuk-developer-docs#1777]
Debugging alerts for licensing is hard because it differs from the standard GOV.UK architecture in some ways, but not in others. It's not something we're actively working on, so there's little shared knowledge about where it exists on GOV.UK and what the different machines are for. 

It was also surprising that it exists in Signon, given that it's commonly referred to as being 'special'. Appreciate all that is quite vague, but some kind of overview doc that explains the support status and touches on the infrastructure and user journeys would be helpful :-).

**Comment by benthorner** [comment]
@stevenjmesser thanks for offering to help with this :-).

**Comment by issyl0** [comment]
Some of this exists in the [legacy opsmanual](https://docs.google.com/document/d/17XUuPaZ5FufyXH00S9qukl6Kf3JbJtAqwHR3eOBVBpI/edit#heading=h.4rr9rzubhak) (page 5), but I'm not sure how up to date it is.

**Comment by stevenjmesser** [comment]
Except for where boxes are located, most of it should be up-to-date.

Also, apologies for not having got around to this, but would the Ops Manual be a good starting point? Could we copy the Licensing section over here?
