### ISSUE TITLE
SSH command generation ambiguous

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk-developer-docs#1803]
See https://docs.publishing.service.gov.uk/apps/email-alert-frontend.html#ssh-access-aws

Recommended SSH command is this:

```
ssh -A -t jumpbox.integration.publishing.service.gov.uk 'ssh `govuk_node_list -c draft_frontend --single-node`'
```

Generated from this logic: https://github.com/alphagov/govuk-developer-docs/blob/master/app/app_docs.rb#L56-L63

## The problem

`email-alert-frontend` [exists in multiple puppet classes](https://raw.githubusercontent.com/alphagov/govuk-puppet/master/hieradata_aws/common.yaml): `frontend` and `draft_frontend`. The command only suggests connecting to `draft_frontend` as this is the first one alphabetically. It would be good to perhaps list _all_ the possible SSH options (i.e. both in this case), rather than pick one arbitrarily.

See:

```
  draft_frontend:
    apps:
      - email-alert-frontend
  frontend:
    apps:
      - email-alert-frontend
```

The proposed solution would therefore be to render this instead:

```
# choose one of the two below
ssh -A -t jumpbox.integration.publishing.service.gov.uk 'ssh `govuk_node_list -c draft_frontend --single-node`'
ssh -A -t jumpbox.integration.publishing.service.gov.uk 'ssh `govuk_node_list -c frontend --single-node`'
```

**Comment by ChrisBAshton** [comment]
Had a little look at this today but easier said than done as we'd have to replicate the logic for both AWS and Carrenza machines, and apps aren't necessarily only running on one cloud host.

**Comment by issyl0** [comment]
Hopefully this will be solved once https://github.com/alphagov/govuk-aws/issues/1159 is done and we can have One Standard Tool for SSH access to all environments.

**Comment by ChrisBAshton** [comment]
This should also not generate dodgy SSH commands like this:

![Screenshot 2020-05-12 at 10 52 46](https://user-images.githubusercontent.com/5111927/81669906-c9a2e300-943e-11ea-859b-fb3ff004c4a6.png)

from https://docs.publishing.service.gov.uk/apps/ckanext-datagovuk.html

**Comment by ChrisBAshton** [comment]
Looks like this is now resolved.
