### ISSUE TITLE
Problem with 'Sidekiq'

### ISSUE THREAD

**Issue by brenetic** [alphagov/govuk-developer-docs#186]
Problem with 'Sidekiq' (https://docs.publishing.service.gov.uk/manual/sidekiq-retries.html)

Sidekiq monitor link at bottom of page is broken

**Comment by brenetic** [comment]
Addressed in https://github.com/alphagov/govuk-developer-docs/pull/189

**Comment by issyl0** [comment]
Closing this as #189 has been merged.
