### ISSUE TITLE
Is it possible to make bluebadge renewal via API?

### ISSUE THREAD

**Issue by AntonVoropaiev** [alphagov/govuk-developer-docs#1880]
Hello! i was trying to find how  i can make blu badge renewal via this API, unfortunately i cant find any endpoint for this task. Is it possible? thanks

**Comment by deanwilson** [comment]
Hi @AntonVoropaiev 

I'm unaware of a way to request a blue badge renewal via the API in general and it would not involve any of the code in this repository as this is mostly developer documentation for our internal systems.
