### ISSUE TITLE
Page "Merge a Pull Request" Has Review Date in the Future 

### ISSUE THREAD

**Issue by martinpeck** [alphagov/govuk-developer-docs#1894]
The "Merge a Pull Request" page states that it was last reviewed in August 2019. At the time of raising this issue, it's July 2019.

![image](https://user-images.githubusercontent.com/1524451/62074274-4ceda200-b23a-11e9-885f-d646c3fe6959.png)

It would appear, from the history for this file, that it was updated in March 2019 as part of commit 8eb20b2, on March 29th 2019. During this commit the following front-matter update was made:

`last_reviewed_on: 2019-02-15`

was changed to

`last_reviewed_on: 2019-08-28`

I suspect the `08` should have been a `03`.

Page: https://docs.publishing.service.gov.uk/manual/merge-pr.html

Source: https://github.com/alphagov/govuk-developer-docs/blob/master/source/manual/merge-pr.html.md

Issue originally spotted by @petevb

**Comment by tijmenb** [comment]
Review dates in the future are now a thing of the past. Thanks @martinpeck and @petevb!
