### ISSUE TITLE
Low available disk space Alert docs

### ISSUE THREAD

**Issue by whi-tw** [alphagov/govuk-developer-docs#2356]
A section needs to be added to this on exactly *how* to extend the disk on EBS-backed Nitro EC2 Instances.

The process we used today to extend a disk w/ lvm on one such machine is below, this could do to be added to the docs in due course:

# Resize nvme ebs drive

1. stop graphite: `initctl stop graphite-web`
    1. check nothing is using the disk any more: `lsof /dev/mapper/graphite-data` (should be no output - if not, try to stop remaining processes)
1. unmount volume: `umount /dev/mapper/graphite-data`
1. stop volume group: `vgchange -a n graphite`
1. identify block device's pci device: 
    ``````
     root@ip-10-13-4-104:~# readlink /sys/block/nvme1n1
    ../devices/pci0000:00/0000:00:1f.0/block/nvme1n1
    ``````
1. remove device: `echo 1 > "/sys/devices/pci0000:00/0000:00:1f.0/remove"`
1. rescan pci bus: `echo 1 > "/sys/bus/pci/rescan"`

> now, lsblk should report the correct size
> if it doesn't, reboot - that will fix it. Then come back and do the rest:

7. resize to new extents: `pvresize /dev/nvme1n1`
1. check pv again to make sure stuff is now correct: `pvdisplay`
1. reactivate vg: `vgchange -ay graphite`
1. extend lvm to new extents: `lvextend -l +100%FREE /dev/mapper/graphite-data`
1. resize filesystem to new extents: `resize2fs /dev/mapper/graphite-data`
1. remount volume: `mount /dev/mapper/graphite-data`
1. restart graphite: `initctl start graphite-web` (and any other services stopped in 2)

**Comment by ChrisBAshton** [comment]
Thanks for raising the issue, Tom. We've got a card on the 2nd line board to get this documented: https://trello.com/c/UM04JQAx/1014-low-available-disk-space-on-root-for-aws-hosted-services
