### ISSUE TITLE
Re: 'Whitehall'

### ISSUE THREAD

**Issue by ianfoster99** [alphagov/govuk-developer-docs#2435]
Problem with 'Whitehall' (https://docs.publishing.service.gov.uk/apis/whitehall.html)

Add your application to this list href is 404'ing
https://github.com/alphagov/whitehall/edit/master/docs/api.html

**Comment by issyl0** [comment]
Thanks for the report, @ianfoster99. I suspect this will be fixed by #2433, but I'll leave this open until that's merged and tested!

**Comment by ianfoster99** [comment]
Thanks for the quick feedback @issyl0
