### ISSUE TITLE
Re: 'SSH into machines'

### ISSUE THREAD

**Issue by risicle** [alphagov/govuk-developer-docs#2632]
Problem with 'SSH into machines' (https://docs.publishing.service.gov.uk/manual/howto-ssh-to-machines.html)

I _think_ the suggested command

```
$ govuk_node_list backend
```

might be out of date? It doesn't seem to like a single bare argument anymore, the above now seems to be achieved by

```
$ govuk_node_list -c backend
```

**Comment by issyl0** [comment]
Thanks for this issue. The `-c` does seem correct, yep. `-c` is short for `--class`, IIRC, and `backend` is a machine class. We'll accept PRs to fix this mistake!

**Comment by risicle** [comment]
You're everywhere aren't you?
