### ISSUE TITLE
Relative links on 'external documentation' don't resolve correctly on docs.publishing.service.gov.uk

### ISSUE THREAD

**Issue by ZacharyForrest** [alphagov/govuk-developer-docs#2851]
Problem with '' (https://docs.publishing.service.gov.uk/apis/search-api/how-search-works.html)

Links e.g <a href="learning-to-rank.md">learning to rank documentation</a> 404

e.g https://docs.publishing.service.gov.uk/apis/search-api/learning-to-rank.md -> 404

but https://docs.publishing.service.gov.uk/apis/search-api/learning-to-rank.html -> this works!

**Comment by ChrisBAshton** [comment]
Thanks @ZacharyForrest - this has been on my list, I've now written up a card for it and look to get to it sometime this month: https://trello.com/c/PLV6EPXh/199-fix-relative-links-images-on-imported-docs
