### ISSUE TITLE
Creating or moving a page gives a nil parsing error

### ISSUE THREAD

**Issue by injms** [alphagov/govuk-developer-docs#2875]
Error message:

```
NoMethodError: undefined method `author_date' for nil:NilClass
```

Steps to replicate:

1. Rename a existing file - for example, changing `redirect-routes.html.md` to `redirect-routes.html.md.erb`. 
1. Run `./startup.sh`
1. Navigate to the new URL for the renamed file - for example, http://localhost:4567/manual/redirect-routes.html

I think that this is due to the file not being committed, which then means that `author_date` can't be found when file's git information is parsed:

https://github.com/alphagov/govuk-developer-docs/blob/25dd4133ef6ad59e55372dcc955949de137e573a/helpers/commit_helpers.rb#L16

My stopgap solution was to commit it locally, then `git commit --amend` for the "real" commit. This also helps solve the other errors thrown by uncommitted files.

Other solutions could be involve using `dig`, or returning `Time.now` when no other time stamp is found?

**Comment by ChrisBAshton** [comment]
Oops - thanks for spotting, @injms!
