### ISSUE TITLE
Broken link on 'Get started on GOV.UK'

### ISSUE THREAD

**Issue by ESKYoung** [alphagov/govuk-developer-docs#3083]
# Problem with ['Get started on GOV.UK'](https://docs.publishing.service.gov.uk/manual/get-started.html)

There's a broken link (link text `hieradata/integration.yaml`) in the ["Create a user to SSH into integration"](https://docs.publishing.service.gov.uk/manual/get-started.html#create-a-user-to-ssh-into-integration) section.

**Comment by AlanGabbianelli** [comment]
Fixed in https://github.com/alphagov/govuk-developer-docs/pull/3085
