### ISSUE TITLE
Re: 'Create a GPG key'

### ISSUE THREAD

**Issue by howff** [alphagov/govuk-developer-docs#3103]
Problem with 'Create a GPG key' (https://docs.publishing.service.gov.uk/manual/create-a-gpg-key.html)

The document says that in the output
```
pub   2048R/90E65803 2013-02-08
```
the Key ID is the part `90E65803`.

But when I run it the output looks like this
```
pub   rsa3072 2021-05-14 [SC] [expires: 2023-05-14]
```
so the key ID appears to be missing.

**Comment by Naradaisthename** [comment]
Interesting

**Comment by richardTowers** [comment]
Closing as we no longer use GPG on GOV.UK, and the docs have been removed.
