### ISSUE TITLE
Re: 'Pact Broker'

### ISSUE THREAD

**Issue by bethesque** [alphagov/govuk-developer-docs#3485]
Problem with 'Pact Broker' (https://docs.publishing.service.gov.uk/manual/pact-broker.html)

Hi. I'm one of the maintainers of the Pact Broker. It was brought to my attention that the instance of the Pact Broker that you are using is 3 years old. I'm not sure if you're using the Docker image or running the vanilla Ruby application, but I do strongly recommend updating, as both the Docker image and the Ruby dependencies will have many vulnerabilities by now.

I recommend using the pactfoundation/pact-broker Docker image if possible. We keep this up to date using vulnerability scanners, and new releases come out every few months at minimum. 

If you have any questions, feel free to join our Slack community at https://slack.pact.io

**Comment by ChrisBAshton** [comment]
Thank you for raising this issue. We identified a problem with our deployment script and this has now been fixed.

Thanks also for your continued good work on Pact Broker!
