### ISSUE TITLE
Re: 'Out of hours support (on-call)'

### ISSUE THREAD

**Issue by lukegb** [alphagov/govuk-developer-docs#3755]
Problem with 'Out of hours support (on-call)' (https://docs.publishing.service.gov.uk/manual/on-call.html)

The oncall checklist has a link to "know how to contact the rest of SMT", which includes a link to a public Google Sheet with personal phone numbers and email addresses on the "rota members' contact details" sheet.

That _feels_ like a bad idea, although possibly someone has evaluated the risks involved and decided it's fine.

**Comment by richardTowers** [comment]
Hi @lukegb - thank you for this report. You're correct that this was not deliberate. I've updated the sharing settings on the document so it should no longer be publicly accessible. We'll treat this as an incident and work through our information governance procedures.
