### ISSUE TITLE
Problem with 'Backup passive checks'

### ISSUE THREAD

**Issue by boffbowsh** [alphagov/govuk-developer-docs#388]
Problem with 'Backup passive checks' (https://docs.publishing.service.gov.uk/manual/alerts/backup-passive-checks.html)

This only covers the false alarm case, but not the case when the backup actually hasn't run at all and needs re-running.

**Comment by issyl0** [comment]
This was partially fixed by e8b9575357486a7f89aa68dea171c2db53eda3ad last year, but only for MongoDB.

**Comment by boffbowsh** [comment]
:wave:

**Comment by issyl0** [comment]
I found this issue and was naturally intrigued as to its resolution (or not). :joy: Hiii! :wave:

**Comment by ChrisBAshton** [comment]
Closing as 'partially fixed' 😄  we can improve the docs next time this comes up.
