### ISSUE TITLE
Consider not importing docs for retired repos

### ISSUE THREAD

**Issue by ChrisBAshton** [alphagov/govuk-developer-docs#3974]
A [search for "deployed-to-production"](https://docs.publishing.service.gov.uk/search/index.html?q=deployed-to-production#search-results) (a git tag that is no longer used in the new platform) returns a number of results for publishing-e2e-tests, which is a [retired repo](https://docs.publishing.service.gov.uk/repos/publishing-e2e-tests.html):

> ![Screenshot 2023-04-25 at 08 44 40](https://user-images.githubusercontent.com/5111927/234208934-478ace43-6cbe-4910-86d5-671a97b7cd0a.png)

This is arguably not useful (in this case, I simply wanted to see what docs need updating, but I'm not going to update docs in retired repos!), and the quantity of imported & retired docs is probably quite considerable and likely to slow down our search experience.

However, there may be some rare cases where it is useful to surface old docs (beyond just the retired repos' READMEs), so give this some more thought or put it to the vote before actioning.

Quick idea: we could also introduce a "Include retired repos?" option in the search form, which would be unchecked by default.

**Comment by sengi** [comment]
I reckon we can call this done.

I don't think implementing a feature to search retired repos via devdocs would be worthwhile. It'd be rarely used, it'd mean we'd still have to scrape all the retired repos (which was making development of devdocs itself painfully slow) and it's trivial to just search GitHub or Sourcegraph if you want to find stuff in our archived repos.
