### ISSUE TITLE
Did you know that you can combine Dependabot PRs into one now, with "groups"?

### ISSUE THREAD

**Issue by issyl0** [alphagov/govuk-developer-docs#4147]
Hey friends!

I couldn't find anywhere better to put this off the top of my head, so here will have to do.

I know that you've historically been busy trying to manage all the Dependabot PRs (the RFCs speak for themselves) across all the repos. I thought you might like a head's up about a beta feature that I just learned about: [groups](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups) and an official [combine PRs](https://github.com/github/combine-prs) Action.

It looks like this is already used in other parts of GDS, notably https://github.com/alphagov/govuk-frontend/pull/3883, in case that's a real-life example that's useful.

I hope that's helpful, or you can tell me to shut up because this was somewhat unsolicited. 😉

**Comment by ChrisBAshton** [comment]
Thanks @issyl0! 👋 

We did notice this new feature, and it's exciting :) But it sort of conflicts with [RFC-156](https://github.com/alphagov/govuk-rfcs/blob/main/rfc-156-auto-merge-internal-prs.md), which is even more exciting (auto merging certain Dependabot PRs), which is the direction we're hoping to travel in.

We are [potentially exploring using Dependabot PR grouping](https://trello.com/c/m2RmBL0A/3037-test-dependabot-grouped-updates-on-psr-repos) for the PRs & repos that don't qualify for RFC-156 (e.g. on non-continuously-deployed repos, or indeed any external dependency updates). 👍 

I'll close this for now as we have this idea covered by the linked Trello card. Thank you for raising though, and nice to hear from you! 😄
