### ISSUE TITLE
Re: 'Analytics on GOV.UK'

### ISSUE THREAD

**Issue by armoj** [alphagov/govuk-developer-docs#4276]
Problem with 'Analytics on GOV.UK' (https://docs.publishing.service.gov.uk/manual/analytics.html)
There is a broken link near the bottom of the page.
Link text: static frontend government-frontend
Link href: https://docs.publishing.service.gov.uk/repos/static%20frontend%20government-frontend.html

**Comment by ChrisBAshton** [comment]
Thanks for spotting this! Looks like it only affects on page. I've raised a PR to fix it now: https://github.com/alphagov/govuk-developer-docs/pull/4277
