### ISSUE TITLE
Re: 'Get started developing on GOV.UK'

### ISSUE THREAD

**Issue by yndajas** [alphagov/govuk-developer-docs#4449]
Problem with 'Get started developing on GOV.UK' (https://docs.publishing.service.gov.uk/manual/get-started.html)

Under "7. Install and configure the GDS CLI" then "4. Set up AWS credentials", the process reports an error at the end for something related to YubiKeys. There's no mention of this in this section of the documentation. Editing `~/.gds/config.yml` and changing `yubikey: true` to `yubikey: false` fixes this issue, as documented [here](https://github.com/alphagov/gds-cli?tab=readme-ov-file#aws-mfa). This page should probably be updated to clarify this step

**Comment by sengi** [comment]
Thanks! Looks like this was independently fixed in the meantime in #4469

**Comment by sengi** [comment]
We should be giving everyone Yubikeys and have modern, unphishable authn ofc, but that's another story 🙃
