### ISSUE TITLE
Re: 'Kubernetes/EKS cheatsheet'

### ISSUE THREAD

**Issue by userbradley** [alphagov/govuk-developer-docs#4528]
Problem with 'Kubernetes/EKS cheatsheet' (https://docs.publishing.service.gov.uk/kubernetes/cheatsheet.html)

The below section has issues, as I believe the indentation causes markdown to render it all as code

![image](https://github.com/alphagov/govuk-developer-docs/assets/41597815/5ab9805b-edf9-4b9e-88f8-f359073560b8)

I would submit a PR to fix this, but I dont have gov.uk docker setup

**Comment by sengi** [comment]
Thanks for spotting this!
