### ISSUE TITLE
Issues with 'Add a new document type'

### ISSUE THREAD

**Issue by tijmenb** [alphagov/govuk-developer-docs#611]
@Davidslv @MatMoore you're set as the owners for:

https://docs.publishing.service.gov.uk/manual/add-a-new-document-type.html
https://docs.publishing.service.gov.uk/manual/make-a-new-document-type-available-to-search.html

Some issues:

- The pages have expired, but the manual spaniel can't handle 2 usernames. Perhaps choose one owner or add it to a channel.
- Pages probably need to go into the "Publishing" section
- https://docs.publishing.service.gov.uk/manual/add-a-new-document-type.html#make-the-new-document-type-available-to-search completely duplicates https://docs.publishing.service.gov.uk/manual/make-a-new-document-type-available-to-search.html

**Comment by MatMoore** [comment]
Hmm I think the intent was to remove the section from add-a-new-document-type. 

I'd suggest setting ownership to the 2nd-line channel for both pages.
