### ISSUE TITLE
Problem with 'Content Store' - missing content

### ISSUE THREAD

**Issue by joelanman** [alphagov/govuk-developer-docs#643]
Problem with 'Content Store' (https://docs.publishing.service.gov.uk/apis/content-store.html)

Some content does not work on the API:

https://github.com/alphagov/content-store/issues/325

However the documentation says that it will:

> The Content Store is the store for all published content on GOV.UK. When given a path, it responds with the content that should be displayed on that path.

I suggest
- explaining what is missing, and
- explain how to check if the API is returning what you asked for, or it's returning another item

**Comment by joelanman** [comment]
related: https://github.com/alphagov/content-store/issues/325

**Comment by MatMoore** [comment]
There is some context about migration status on the wiki here https://gov-uk.atlassian.net/wiki/spaces/GPM/pages/61505540/Migration+progress

It would be good to incorporate this information into the developer docs so it's easier to find. It's not being actively updated at the moment.

**Comment by thomasleese** [comment]
I've put in a PR to update the Content Store docs to link to the Content API docs (#645), and updated the Content API docs to include a sentence about what you might get back from the API if you query for an unmigrated piece of content. I'll leave this issue open though as the information available on Confluence should definitely be incorporated into the documentation.

**Comment by tijmenb** [comment]
I think the missing content alluded to by @joelanman are the Whitehall pages that aren't in the publishing-api/content-store at all, not just pages that are placeholder in the content-store. @joelanman did you find other pages than the history pages like `/government/history/past-prime-ministers/gordon-brown` you mentioned in https://github.com/alphagov/content-store/issues/325?

**Comment by joelanman** [comment]
It was a long time ago, but I don't remember any other missing pages specifically.
