### ISSUE TITLE
Problem with ''uptime metrics" link - not responding due to time out

### ISSUE THREAD

**Issue by pipesdreams** [alphagov/govuk-developer-docs#727]
Problem with '' (https://docs.publishing.service.gov.uk/apps/publishing-api.html) - the "Uptime Metrics" link, https://grafana.publishing.service.gov.uk/dashboard/file/application_uptime.json is not loading. ERR_CONNECTION_TIMED_OUT

**Comment by MatMoore** [comment]
Hi @pipesdreams, unfortunately that dashboard is not publicly accessible at the moment, as it's one of our internal grafana dashboards that we use to debug our applications. These docs are intended for developers at GDS who work on GOV.UK.

If you don't mind me asking, what interests you in these metrics? My current team is reviewing how we measure GOV.UK more generally, and we'd be interested to hear about other ways our data could be useful.

**Comment by pipesdreams** [comment]
Hi Mat,

I work for the Province of Ontario in Canada, as QA Lead for Ontario.ca - we are always doing scans of other governments to see how they handle their online presence, and my particular areas of interest are documentation and metrics, since both are crucial to QA practice. 

Without developer docs, it’s extremely difficult to determine root cause of a bug, since it’s possible that the system was designed in a certain way because the developer and business had different interpretations of the requirements. 

The Ontario Digital Service has a very small technical staff complement, so my QA mandate is very broad - I look at front end, back end, help with release management, review Git and act as a de facto technical writer on the side. 

Hope that explains why I was attempting to access your hidden dashboards. Please don’t send MI5 after me - I’ve seen Spooks and that episode with the deep fat fryer still haunts me.

Cheers,
Moira

**Comment by deanwilson** [comment]
An old issue with a wonderful journey inside. Closing with a smile.
