### ISSUE TITLE
Problem with 'Get started on GOV.UK'

### ISSUE THREAD

**Issue by kdziubacaci** [alphagov/govuk-developer-docs#784]
Problem with 'Get started on GOV.UK' (https://docs.publishing.service.gov.uk/manual/get-started.html)

Is this https://docs.publishing.service.gov.uk/manual/get-started.html and others 
intended to be open widely to the public?

**Comment by tijmenb** [comment]
Hi @kdziubacaci, that's correct. At GDS we work try to work in the open as much as possible.

You can read more about the approach here:

https://gds.blog.gov.uk/2017/09/04/the-benefits-of-coding-in-the-open/
