### ISSUE TITLE
Using comments in codeblocks makes tests fail

### ISSUE THREAD

**Issue by rossjones** [alphagov/govuk-developer-docs#933]
It appears as if the presence of a comment in a codeblock, where that comment is a # character, fails the following test.  This probably isn't easily fixable, but perhaps it would be possible to suggest it as a source of errors when this fails?

```
      it "doesn't use H1 tags (the page title is already an H1)" do
        expect(raw).not_to match(/\n#\s/)
      end
```

**Comment by tijmenb** [comment]
Hah yes, that's something I couldn't work out how to fix. There's a whitelist for this case: https://github.com/alphagov/govuk-developer-docs/blob/master/spec/pages/manual_page_spec.rb#L30-L32

Suggesting it as a source of errors would be great!
