### ISSUE TITLE
Skyscape status url

### ISSUE THREAD

**Issue by Davidslv** [alphagov/govuk-developer-docs#993]
In this document https://github.com/alphagov/govuk-developer-docs/blob/master/source/manual/alerts/pingdom-homepage-check.html.md

The Skyscape status url seems to not be accessible.

**Comment by issyl0** [comment]
This hasn't been updated since SkyScape's rename to UKCloud. The correct link is https://status.ukcloud.com/.

**Comment by Davidslv** [comment]
Thank you @issyl0, will correct it

**Comment by Davidslv** [comment]
https://github.com/alphagov/govuk-developer-docs/pull/994
